### ISSUE TITLE
side menu only on specific sites

### ISSUE THREAD

**Issue by achtan** [meteoric/meteor-ionic#219]
Hi, i want that side menu will by visible only on certain sites
how can i achieve that?

**Comment by codingInSpace** [comment]
Hi. I don't know if there's a better solution, but I was able to do it for my scenario by calling IonSideMenu.snapper.disable(). Disabling the snapper only actually disables the drag functionality for the side bar, but if you do it as you're routing to a page that doesn't have the header button for it, it's inaccessible.

So I'm making an app where a logged out user only has access to a login page and a signup page. I don't want a sidebar available here. The layout template is called appLayout, and in its js file:

```javascript
Template.appLayout.rendered = function () {
  if ((Router.current().route.getName() === 'signup') ||
     (Router.current().route.getName() === 'login')) {
    // console.log("turning off side menu");
    IonSideMenu.snapper.disable();
  }
};
```

signup and login are the templates and route names for the two pages a logged out user gets.

Also where I'm handling the logout functionality:
```javascript
Meteor.logout(function(error) {
  if(error) {
      //display error
      console.log("logout error: " + error);
  } else {
      IonSideMenu.snapper.disable(); //disable side bar
      Router.go('/login');
  }
});
```
This disables the side bar as the login and signup pages are loaded.

And then, because the page the router routes to as a user is logged in (and should start being able to access the side bar) is called tasks, I enable it again for this page. It's now enabled for any other page the user would go to except when logging back out to the login/signup pages. The if-statement isn't necessary here
```javascript
Template.tasks.rendered = function () {
  if (Router.current().route.getName() === 'tasks') {
    // console.log("turning on side menu");
    IonSideMenu.snapper.enable();
  }
};
```

My app is here, https://github.com/codingInSpace/getbusy

**Comment by geritol** [comment]
Or you can use other layout template for routes with side menu. So you don't have to deal with opening closing, enabling disabling it.
