### ISSUE TITLE
Please mark as depreciated

### ISSUE THREAD

**Issue by der-ede** [meteoric/meteor-ionic#362]
Hi nick

As you stated in https://github.com/meteoric/meteor-ionic/issues/353 and other issues you don't want to maintain the package anymore. Personally I can understand that, but also the well explained read me file and the professional logo give the impression of a professional package. We implemented everything with meteoric and now we cannot even run it in iOS 9.1 so we have to program everything new in a professional project in our company.
That will be at least 2-4 weeks of extra work, while we were actually planning to ship next week, so maybe you could please  tell us about your decision in the readme as it is custom practice in github.

Or maybe someone could tell us how we change the source so we can ship to iOS 9.1?

Thank you and regards

**Comment by nickw** [comment]
Sorry about that, I just updated the README.

**Comment by DanielDornhardt** [comment]
Hello @der-ede , can you please explain to me what the issue is with meteor-ionic / ionic and iOS 9.1? What's the general issue? Because we're running on Meteoric as well and that would of course be a bad thing(tm).

**Comment by der-ede** [comment]
Hello,

We are tracking down the error right now.
But since we found out that the demo app of meteoric is running correctly
in 9.1 it is probably a bug on our side.
Seems like one has to be very precise about the structure of ionView,
ionNavview, ionContent and such and also it would be advisable to deploy to
the iPhone during the development process and not only to test on
emulator/browser.



Am Donnerstag, 10. Dezember 2015 schrieb Daniel Dornhardt :

**Comment by DanielDornhardt** [comment]
Hi @der-ede, thanks for responding so quickly.

I was a bit confused why Meteoric shouldn't work at all with iOS 9.1 anymore to be honest - because it's (almost) all just HTML + CSS in the end, isn't it? At least from the meteoric side of things...

So there had to be a pretty fundamental shift like a new incompatible browser engine in 9.1 or something like this, which would then probably break all recent ionic apps, not only meteoric apps, or so my thoughts went.

+1 to always test on real devices too, we also had some differences appear already between emulator and real devices, especially for things to do with native keyboard handling I think.

Thanks and best wishes!

**Comment by der-ede** [comment]
@DanielDornhardt, A fundamental shift can also be having to trust into/rely on staff as opposed to developing everything by oneself :)
