### ISSUE TITLE
IonicNavButtons

### ISSUE THREAD

**Issue by cryptoquick** [meteoric/meteor-ionic#98]
I'm trying the following, adapted from the instructions for Ionic, but I'm not seeing anything show up:

```handlebars
  {{#ionBody class=activeRoute}}

    {{>ionNavBar class="bar-positive"}}

    {{#ionNavView}}

      {{#ionView}}

        {{#ionNavButtons side="left"}}

          <button menu-toggle="left" class="button button-icon icon ion-navicon"></button>

        {{/ionNavButtons}}

        {{#ionContent}}
          {{> yield}}
        {{/ionContent}}

      {{/ionView}}

    {{/ionNavView}}

  {{/ionBody}}
```

Specifically, I mean the instructions here: http://ionicframework.com/docs/api/directive/ionNavButtons/

I'm just wondering, am I doing something wrong, or is this feature unimplemented in Meteoric?

**Comment by nickw** [comment]
Yeah we don't necessarily have a 1:1 mapping between Ionic components due to various differences between Meteor and Angular. You'll want to check the list of components before attempting to implement one: https://github.com/meteoric/meteor-ionic/tree/master/components

For what you're trying to do you can just use iron:router regions inside your templates: https://github.com/meteoric/meteorhunt/blob/master/client/templates/products/productsShow.html#L3-L15
